### ISSUE TITLE
Why does project have 200+ warnings?

### ISSUE THREAD

**Issue by abelondev** [cometchat-pro/ios-swift-chat-app#26]

**Comment by pushpsenairekar2911** [comment]
Hello, 

Can you share with us the screenshot for the warnings which you're getting. 

Thanks.

**Comment by abelondev** [comment]
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/8701884/125838222-b1041f8c-b8e8-49e2-abfa-ae27a02eab7b.png">

**Comment by pushpsenairekar2911** [comment]
Hello @abelondev, 

We'll try to reduce those warnings in upcoming releases of UI Kit. But as of now, it won't affect the performance and usability of the UI Kit. 
Please, feel free to use and customize it as per your requirement. Also, watch this repo so that you'll get notified when we release a new version of our UI Kit. 

Regards, 
Pushpsen R. Airekar
